logging:
  level:
    root: INFO
    br.com.beblue: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/votacao_service
    password: votacao_service
    username: votacao_service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
    show-sql: false

  rabbitmq:
    addresses: amqp://rabbit:5672

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher